[package]
name = "adsb-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "adsb"
path = "src/main.rs"

[dependencies]
adsb-core = { path = "../adsb-core" }
clap = { version = "4", features = ["derive"] }
comfy-table = "7"
